# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Gateway Tests CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Install dependencies    
      run: npm ci

    - name: Make shell executable
      run: |
        chmod +x start.sh
        chmod +x stop.sh


    - name: Start app via containers
      run: ./start.sh
      env:
        COMPOSE_FILE: docker/docker-compose.yml

    - name: Verify app is running
      run: |
          echo "Waiting for app to start on port 8002..."
          npx wait-on http://localhost:8002 --timeout 60000
          echo "App is running!"

    - name: Run Cypress tests
      uses: cypress-io/github-action@v5
      with:
        headless: true
        config-file: cypress.config.js
        command: npm run test:ci

    - name: Cleanup Docker resources
      if: always()
      run: |
        docker system prune -f
        docker volume prune -f
